{% set version = "2.4.1" %}

package:
    name: mkl-service
    version: {{ version }}

source:
    url: https://github.com/IntelPython/mkl-service/archive/v{{ version }}.tar.gz
    sha256: e9a587b49779f189744db99bece85fd1e51d9113d708de45889f7f9aaaa51e2d

build:
    number: 0
    ignore_run_exports:
      - blas
      - mkl-service

requirements:
    build:
      - {{ compiler('c') }}
    host:
      - python
      - setuptools
      - mkl-devel
      - cython
    run:
      - python
      - mkl

test:
    requires:
      - pytest
    imports:
      - mkl
    commands:
      - pytest -vv --pyargs mkl

about:
    home: http://github.com/IntelPython/mkl-service
    license: BSD-3-Clause
    license_file: LICENSE.txt
    license_family: BSD
    description:
        Intel(R) Math Kernel Library (Intel(R) MKL) support functions are
        subdivided into the following groups according to their purpose, such as
            Version Information
            Threading Control
            Timing
            Memory Management
            Conditional Numerical Reproducibility Control
            Miscellaneous
    summary: Python hooks for Intel(R) Math Kernel Library runtime control settings.

extra:
  recipe-maintainers:
     - oleksandr-pavlyk
