{% set version = "2.9.0" %}

package:
  name: mkl-service
  version: {{ version }}

source:
  url: https://github.com/IntelPython/mkl-service/archive/{{ version }}.tar.gz
  sha256: 61cc4bfadb390c9d1adb8293df1b5d901f34a9cce947253775d8de9175ed1453

build:
  number: 0
  skip: true  # [osx and arm64]
  ignore_run_exports:
    - blas
    - mkl-service

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - meson-python >=0.13.0
    - cmake
    - ninja
    - mkl-devel <2024  # [osx]
    - mkl-devel  # [not osx]
    - cython >=3.1.0
  run:
    - python
    - mkl

test:
  requires:
    - pip
    - pytest
  imports:
    - mkl
  commands:
    - pip check
    - pytest -vv --pyargs mkl

about:
  home: https://github.com/IntelPython/mkl-service
  license: BSD-3-Clause
  license_file: LICENSE.txt
  license_family: BSD
  description: >-
    Intel® oneAPI Math Kernel Library (oneMKL) support functions are subdivided
    into the following groups according to their purpose: Version Information,
    Threading Control, Timing, Memory Management, Conditional Numerical
    Reproducibility Control, and Miscellaneous.
  summary: Python hooks for Intel® oneAPI Math Kernel Library (oneMKL) runtime control settings

extra:
  recipe-maintainers:
    - ekomarova
    - napetrov
    - vtavana
    - xaleryb
    - jharlow-intel
    - antonwolfy
